### ISSUE TITLE
UDs isasimple : handle studies with dots in name

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/vdi-plugin-isasimple#3]
nov 29 2023 steve slacks: "john agreed to transform silly characters into _ in the vdi plugin"

this happens in eda065s, a user study 4099029 user_id 299468013
 
currently we remove dots to create tables, but not to create ancestor stable_ids, and that eventually breaks a basic SQL.

select table_name from all_tables where table_name like '%20231110013428_WXIY%';
ANCESTORS_AUTO_20231110013428_WXIY_1_KPNEUMONIAE_EPIDEMIOLOGY_KENYA_10_NOV_23
ATTRIBUTEGRAPH_AUTO_20231110013428_WXIY_1_KPNEUMONIAE_EPIDEMIOLOGY_KENYA_10_NOV_23
ATTRIBUTES_AUTO_20231110013428_WXIY_1_KPNEUMONIAE_EPIDEMIOLOGY_KENYA_10_NOV_23

select * from apidbuserdatasets.ANCESTORS_AUTO_20231110013428_WXIY_1_KPNEUMONIAE_EPIDEMIOLOGY_KENYA_10_NOV_23 order by KPNEUMONIAE_EPIDEMIOLOGY_KENYA_10_NOV_23_STABLE_ID;
k.pneumoniae_epidemiology_kenya_10_nov_23:1
k.pneumoniae_epidemiology_kenya_10_nov_23:10
k.pneumoniae_epidemiology_kenya_10_nov_23:11

broken:
WITH
TEMP_k.pneumoniae_epidemiology_kenya_10_nov_23 as
 (
  SELECT KPneumoniae_epidemiology_kenya_10_nov_23_stable_id FROM apidbuserdatasets.ancestors_auto_20231110013428_WXiY_1_KPneumoniae_epidemiology_kenya_10_nov_23
)
SELECT count(distinct KPneumoniae_epidemiology_kenya_10_nov_23_stable_id) as count
FROM (
  SELECT distinct TEMP_k.pneumoniae_epidemiology_kenya_10_nov_23.KPneumoniae_epidemiology_kenya_10_nov_23_stable_id
  FROM TEMP_k.pneumoniae_epidemiology_kenya_10_nov_23
)

**Comment by danicahelb** [comment]
please fix asap as we are getting complaints from users. thanks!

**Comment by steve-fischer-200** [comment]
VDI will fix this
